---
   - name: yum_install_packages
     yum: name={{item}}  state=present
     with_items:
      - authconfig
      - openldap-clients
      - nss-pam-ldapd

   - name: add_ldap_kazunori_51S
     shell: authconfig --enableldap --enableldapauth --ldapserver="ldap://10.1.0.52/" --ldapbasedn="dc=example,dc=com" --enablemkhomedir --update

   - name: chkconfig on
     service: name=nslcd enabled=yes

   - name: add kazunori as sudo user
     copy: >
         src=kazunori
         dest=/etc/sudoers.d/kazunori
         owner=root
         group=root
         mode=0644


   - name: install zabbix repo
     yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present

   - name: install zabbix_agent
     yum: name=zabbix-agent  state=present

   - name: set config file
     template: src=zabbix_agentd.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644

   - name: service zabbix_agent restart
     service: name=zabbix-agent state=restarted enabled=yes
