---
  - name: yum install bind
    yum: name=bind state=present 
  
  - name: set /etc/named.conf
    template: src=named.j2 dest=/etc/named.conf owner=root group=named mode=0640

  - name: set /var/named/kazutan.com.lan
    template: src=kazutan.com.lan.j2 dest=/var/named/kazutan.com.lan owner=root group=named mode=0640

  - name: renew named.ca
    shell: wget ftp://ftp.nic.ad.jp/internet/rs.internic.net/domain/named.root -O /var/named/named.ca

  - name: set /etc/resolv.conf
    template: src=resolve.j2 dest=/etc/resolv.conf owner=root group=named mode=0644

  - name: service named start
    service: name=named state=started enabled=yes
